blackbox_sources += files(
  'AboutDialog.vala',
  'ColorSchemeThumbnail.vala',
  'HeaderBar.vala',
  'SearchToolbar.vala',
  'ShortcutDialog.vala',
  'ShortcutEditor.vala',
  'PreferencesWindow.vala',
  'StyleSwitcher.vala',
  'Terminal.vala',
  'TabStrip.vala',
  'TerminalTab.vala',
  'Window.vala',
)
